### ISSUE TITLE
Missing LICENSE file.

### ISSUE THREAD

**Issue by ericsnowcurrently** [foliojs/restructure#32]
I found 2 license-related problems:

- [ ] missing `LICENSE` file at top of repo
   + it should contain your copyright info
   + you've indicated MIT: https://opensource.org/licenses/MIT
- [ ] missing `LICENSE` file in the release tarball (under https://registry.npmjs.org/)

**Comment by devongovett** [comment]
Fixed by 5cb1826410000af0c0294dda2db783437d016c9f.
