### ISSUE TITLE
Causing unsafe eval issue: is it solved?

### ISSUE THREAD

**Issue by davidecantini** [foliojs/restructure#44]
There's an [issue in pdfmake](https://github.com/bpampuch/pdfmake/issues/1360#issuecomment-674282123) which is said to be caused by restructure.
Can you please confirm whether that is fixed in the current version or not yet? Thank you.

**Comment by liborm85** [comment]
Yes, it is solved - https://github.com/bpampuch/pdfmake/issues/2282
