### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by capc0** [foliojs/restructure#45]
since https://github.com/foliojs/restructure/commit/dd343b00ad9d536c84deb08a50473011273c5c25 has been merged, it would be highly appreciated if you can cut a new release

**Comment by liborm85** [comment]
For release have persmissions only @devongovett, but he is inactive.

**Comment by ajayep** [comment]
Hi @devongovett ,
Can you please look into making the release ? Wishing you a happy new year 2021 :)

**Comment by capc0** [comment]
bump

**Comment by jeetiss** [comment]
I have avatar, maybe this help))

@devongovett can you make new release

**Comment by liborm85** [comment]
@capc0 @ajayep @jeetiss You can use up-to-date fork https://github.com/foliojs-fork/restructure.

**Comment by devongovett** [comment]
A release was cut a while ago.
