### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by diegomura** [foliojs/restructure#49]
Running restructure in node throws `ReferenceError: TextEncoder is not defined`. 
I think it's because TextEncoder is exported via `util.TextEncoder`
Currently blocking `react-pdf` migration to mainline fontkit repo [here](https://github.com/diegomura/react-pdf/pull/1908)

**Comment by devongovett** [comment]
Should be available globally as of node 11. What version are you using?

**Comment by diegomura** [comment]
Weird. Node 12 🤔 I'll test again later today

**Comment by diegomura** [comment]
I confirmed I'm using v12 and that `TextEncoder` is globally defined. However, tests are failing ([here](https://github.com/diegomura/react-pdf/runs/7160517101?check_suite_focus=true#step:6:689)) and cannot figure out why. It fails at `../../node_modules/restructure/dist/src/EncodeStream.js:3:21` which doesn't seem to be a valid path on the latest restructure build

**Comment by diegomura** [comment]
Was an issue with jsdom not defining those globals apparently. Fixed

**Comment by pablohenriqueop** [comment]
@diegomura Hi Diego, how did you solve this problem? I'm facing exactly the same problem. My node version: `16.16.0`
