### ISSUE TITLE
Unsupported string encodings

### ISSUE THREAD

**Issue by timmyL17** [foliojs/restructure#60]
Hi,

It looks like the newest version 3.0.1 has broken support for some string encodings, like `x-mac-roman`, because the `encodingWidth` function in `String.js` only supports a few options. I noticed this because `fontkit` on mac was using `x-mac-roman` for some of the strings.

**Comment by srl295** [comment]
maybe the cause of #61

**Comment by srl295** [comment]
@timmyL17 can you provide a reproducer?

**Comment by srl295** [comment]
@mcdurdin fyi
